ROLE_SKILLS = {
    "Backend Developer": [
        "python",
        "fastapi",
        "sql",
        "rest api",
        "docker",
        "deployment",
        "testing",
        "git",
    ],
    "Data Scientist": [
        "python",
        "pandas",
        "numpy",
        "machine learning",
        "statistics",
        "sql",
        "visualization",
        "deployment",
    ],
    "AI Engineer": [
        "python",
        "deep learning",
        "transformers",
        "nlp",
        "pytorch",
        "fastapi",
        "deployment",
        "mlops",
    ],
    "Frontend Developer": [
        "react",
        "javascript",
        "typescript",
        "css",
        "tailwind",
        "accessibility",
        "testing",
        "state management",
    ],
    "Full Stack Developer": [
        "react",
        "node",
        "sql",
        "rest api",
        "docker",
        "git",
        "testing",
        "deployment",
    ],
    "DevOps Engineer": [
        "linux",
        "docker",
        "kubernetes",
        "ci/cd",
        "aws",
        "terraform",
        "monitoring",
        "security",
    ],
    "Cloud Engineer": [
        "aws",
        "azure",
        "networking",
        "terraform",
        "kubernetes",
        "security",
        "monitoring",
        "deployment",
    ],
    "ML Engineer": [
        "python",
        "machine learning",
        "pytorch",
        "feature engineering",
        "mlops",
        "deployment",
        "sql",
        "statistics",
    ],
    "Prompt Engineer": [
        "prompt engineering",
        "llms",
        "nlp",
        "evaluation",
        "analytics",
        "communication",
        "problem solving",
        "data structures",
    ],
    "Data Engineer": [
        "python",
        "sql",
        "etl",
        "spark",
        "airflow",
        "data warehousing",
        "aws",
        "deployment",
    ],
    "Product Manager": [
        "analytics",
        "communication",
        "problem solving",
        "agile",
        "prioritization",
        "execution",
        "stakeholder management",
        "roadmapping",
    ],
    "QA Engineer": [
        "testing",
        "automation",
        "api",
        "regression",
        "documentation",
        "git",
        "problem solving",
        "communication",
    ],
    "Security Engineer": [
        "security",
        "owasp",
        "networking",
        "linux",
        "monitoring",
        "incident response",
        "aws",
        "azure",
    ],
    "Mobile Developer": [
        "react",
        "javascript",
        "typescript",
        "rest api",
        "testing",
        "git",
        "deployment",
        "problem solving",
    ],
    "UI/UX Designer": [
        "design systems",
        "wireframing",
        "prototyping",
        "accessibility",
        "communication",
        "research",
        "problem solving",
        "documentation",
    ],
    "Business Analyst": [
        "requirements",
        "process mapping",
        "sql",
        "analytics",
        "communication",
        "documentation",
        "problem solving",
        "stakeholder management",
    ],
    "Site Reliability Engineer": [
        "linux",
        "kubernetes",
        "monitoring",
        "automation",
        "aws",
        "ci/cd",
        "incident response",
        "problem solving",
    ],
    "Solutions Architect": [
        "system design",
        "aws",
        "azure",
        "security",
        "scalability",
        "communication",
        "documentation",
        "integration",
    ],
    "Technical Writer": [
        "documentation",
        "api",
        "communication",
        "research",
        "git",
        "editing",
        "information architecture",
        "problem solving",
    ],
    "Growth Engineer": [
        "analytics",
        "a/b testing",
        "javascript",
        "automation",
        "reporting",
        "communication",
        "problem solving",
        "sql",
    ],
}
